// GENERATED by tools/rehand.mjs and tools/unroam.mjs. Do not hand-edit.
//
// Corrected hand assignments, committed as data rather than computed at load,
// so what the learner receives is what is in the file. songs.mjs asserts the
// length matches, so a song edited without re-running these tools fails loudly
// instead of being silently mis-handed.
export const REHANDED = {
 "interstellar": {
  "hands": "LLLLLLLLLLLLLLLLRLLLLLRLLLLLLLLLRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRLRRRRRRRRLRRRRRRRRLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRLRRRRLRRLRRRRLRRLRRRRLRRLRRRRLRRRLRRRRLRRLRRRRLRRRRRRRLRRRRRRRRRRRRRRRRRLLLLLRRRRRRLRRLLLLLRRRRRRLLLLLRRRRRLRRLLLLLRRRRRRLRRRRRRRRRRRLRRRRRRRRRRRRRRLRRRLRRRLRRRRRRRRRRRRRRLLRRRRLRRRRLRRLRRRRRRRRRLLRRRRLRRRLRRLRRRRRRRLRRLLRRRRLRRRLRRLLRRRRRRRRLLRRRRLRRRLRRLRRRRLLRRRRRRRRRRRRLLRRRRRRRRRRRRLLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
  "notes": 799
 },
 "hotel-california-easy": {
  "moves": [
   {
    "b": 113,
    "m": 50,
    "from": "L",
    "to": "R"
   },
   {
    "b": 179.5,
    "m": 50,
    "from": "L",
    "to": "R"
   },
   {
    "b": 252,
    "m": 48,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 791
 },
 "piano-man-hard": {
  "moves": [
   {
    "b": 5,
    "m": 67,
    "from": "L",
    "to": "R"
   },
   {
    "b": 8,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 11,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 13,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 17,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 22,
    "m": 65,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 82
 },
 "game-of-thrones-hard": {
  "moves": [
   {
    "b": 71,
    "m": 60,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 306
 },
 "interstellar-easy": {
  "moves": [
   {
    "b": 18.75,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 18.75,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 20.25,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 21.75,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 25,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 28,
    "m": 55,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 203
 },
 "what-ive-done-hard": {
  "moves": [
   {
    "b": 23.5,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 258.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 259,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 259.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 260,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 260.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 261,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 261.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 262,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 274.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 275,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 275.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 277.5,
    "m": 50,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1854
 },
 "work-this-time-hard": {
  "moves": [
   {
    "b": 167,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 167.5,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 159,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 159.5,
    "m": 62,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 460
 },
 "fur-elise-hard": {
  "moves": [
   {
    "b": 306.5,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 142,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 142.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 143,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 143.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 145.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 146.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 160,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 162.5,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 162.5,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 163,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 163,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 165,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 166,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 168.5,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 168.5,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 169,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 169,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 171.5,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 172.5,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 309.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 311.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 311.5,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 312.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 312.5,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 314.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 314.5,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 315.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 315.5,
    "m": 64,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1040
 },
 "light-of-the-seven": {
  "moves": [
   {
    "b": 357.5,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 665,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 665.5,
    "m": 60,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 2172
 },
 "light-of-the-seven-easy": {
  "moves": [
   {
    "b": 389.25,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 446,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 461.25,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 561,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 561.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 561.5,
    "m": 55,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1318
 },
 "mozart-pc21-2": {
  "moves": [
   {
    "b": 123,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.25,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.75,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 131.5,
    "m": 79,
    "from": "L",
    "to": "R"
   },
   {
    "b": 248.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 250.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 267,
    "m": 79,
    "from": "L",
    "to": "R"
   },
   {
    "b": 267.25,
    "m": 82,
    "from": "L",
    "to": "R"
   },
   {
    "b": 275,
    "m": 77,
    "from": "L",
    "to": "R"
   },
   {
    "b": 275.25,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 379,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.25,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.75,
    "m": 67,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1440
 },
 "mozart-pc21-2-easy": {
  "moves": [
   {
    "b": 123,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.25,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.75,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 248.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 250.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.25,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.75,
    "m": 67,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 646
 }
};
