// GENERATED by keys-piano-tools/write-meter.mjs. Do not hand-edit.
//
// Time signatures HEARD from the source recordings, not assumed. The
// transcriber emits no meter at all, so without this every transcribed song
// wore a 120bpm 4/4 grid and Married Life - a waltz - counted in four until
// Mark heard it and said so.
//
// Only songs whose evidence separates clearly appear here; the rest stay
// "free time" and show no time signature, which is the honest state. Keyed by
// song GROUP, since tiers share one recording.
export const METER = {
 "coffin-dance": {
  "meter": 4,
  "beatBpm": 123.1,
  "barSec": 1.95,
  "margin": 0.772,
  "from": "coffin-dance"
 },
 "gladiator": {
  "meter": 4,
  "beatBpm": 152,
  "barSec": 1.58,
  "margin": 0.617,
  "from": "gladiator"
 },
 "imperial-march": {
  "meter": 4,
  "beatBpm": 103.4,
  "barSec": 2.32,
  "margin": 0.344,
  "from": "imperial-march"
 },
 "last-friday-night": {
  "meter": 4,
  "beatBpm": 123.1,
  "barSec": 1.95,
  "margin": 2.781,
  "from": "last-friday-night"
 },
 "married-life": {
  "meter": 3,
  "beatBpm": 184.6,
  "barSec": 0.98,
  "margin": 2.123,
  "from": "married-life-kyle"
 },
 "never-gonna-2": {
  "meter": 4,
  "beatBpm": 172.3,
  "barSec": 1.39,
  "margin": 4.238,
  "from": "never-gonna-2"
 },
 "next-episode": {
  "meter": 4,
  "beatBpm": 95.7,
  "barSec": 2.51,
  "margin": 1.292,
  "from": "next-episode"
 }
};
