// GENERATED by tools/rehand.mjs, tools/unroam.mjs and tools/rehand-safe.mjs.
// Do not hand-edit.
//
// Corrected hand assignments, committed as data rather than computed at load,
// so what the learner receives is what is in the file. songs.mjs asserts the
// length matches, so a song edited without re-running these tools fails loudly
// instead of being silently mis-handed.
export const REHANDED = {
 "interstellar": {
  "hands": "LLLLLLLLLLLLLLLLRLLLLLRLLLLLLLLLRLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRRRRLRRRRRRRRLRRRRRRRRLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRRRRLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRLRRLRRRRLRRLRRRRLRRLRRRRLRRLRRRRLRRRLRRRRLRRLRRRRLRRRRRRRLRRRRRRRRRRRRRRRRRLLLLLRRRRRRLRRLLLLLRRRRRRLLLLLRRRRRLRRLLLLLRRRRRRLRRRRRRRRRRRLRRRRRRRRRRRRRRLRRRLRRRLRRRRRRRRRRRRRRLLRRRRLRRRRLRRLRRRRRRRRRLLRRRRLRRRLRRLRRRRRRRLRRLLRRRRLRRRLRRLLRRRRRRRRLLRRRRLRRRLRRLRRRRLLRRRRRRRRRRRRLLRRRRRRRRRRRRLLRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
  "notes": 799
 },
 "hotel-california-easy": {
  "moves": [
   {
    "b": 113,
    "m": 50,
    "from": "L",
    "to": "R"
   },
   {
    "b": 179.5,
    "m": 50,
    "from": "L",
    "to": "R"
   },
   {
    "b": 252,
    "m": 48,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 791
 },
 "piano-man-hard": {
  "moves": [
   {
    "b": 5,
    "m": 67,
    "from": "L",
    "to": "R"
   },
   {
    "b": 8,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 11,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 13,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 17,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 22,
    "m": 65,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 82
 },
 "game-of-thrones-hard": {
  "moves": [
   {
    "b": 71,
    "m": 60,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 306
 },
 "interstellar-easy": {
  "moves": [
   {
    "b": 18.75,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 18.75,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 20.25,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 21.75,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 25,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 28,
    "m": 55,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 203
 },
 "what-ive-done-hard": {
  "moves": [
   {
    "b": 23.5,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 258.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 259,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 259.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 260,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 260.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 261,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 261.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 262,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 274.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 275,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 275.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 277.5,
    "m": 50,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1854
 },
 "work-this-time-hard": {
  "moves": [
   {
    "b": 167,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 167.5,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 159,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 159.5,
    "m": 62,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 460
 },
 "fur-elise-hard": {
  "moves": [
   {
    "b": 306.5,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 142,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 142.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 143,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 143.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 145.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 146.5,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 160,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 162.5,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 162.5,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 163,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 163,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 165,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 166,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 168.5,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 168.5,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 169,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 169,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 171.5,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 172.5,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 309.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 311.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 311.5,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 312.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 312.5,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 314.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 314.5,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 315.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 315.5,
    "m": 64,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1040
 },
 "light-of-the-seven": {
  "moves": [
   {
    "b": 357.5,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 665,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 665.5,
    "m": 60,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 2172
 },
 "light-of-the-seven-easy": {
  "moves": [
   {
    "b": 389.25,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 446,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 461.25,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 561,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 561.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 561.5,
    "m": 55,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1318
 },
 "mozart-pc21-2": {
  "moves": [
   {
    "b": 123,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.25,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.75,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 131.5,
    "m": 79,
    "from": "L",
    "to": "R"
   },
   {
    "b": 248.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 250.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 267,
    "m": 79,
    "from": "L",
    "to": "R"
   },
   {
    "b": 267.25,
    "m": 82,
    "from": "L",
    "to": "R"
   },
   {
    "b": 275,
    "m": 77,
    "from": "L",
    "to": "R"
   },
   {
    "b": 275.25,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 379,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.25,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.75,
    "m": 67,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1440
 },
 "mozart-pc21-2-easy": {
  "moves": [
   {
    "b": 123,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.25,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.75,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 248.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 250.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.25,
    "m": 67,
    "from": "R",
    "to": "L"
   },
   {
    "b": 379.75,
    "m": 67,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 646
 },
 "in-the-end-hard": {
  "moves": [
   {
    "b": 33,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 41,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 69,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 70,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 77,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 85,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 86,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 93,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 97.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 98.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 101,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 111,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 113.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 114.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 117,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 129,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 137,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 165,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 166,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 173,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 182,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 189,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 193.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 194.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 197,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 207,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 209.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 210.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 213,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 261.5,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 262.5,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 265.5,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 273.5,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 285.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 286.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 289,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 290,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 294.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 297,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 307,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 309.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 310.5,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 313,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 323,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 16,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 24,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 34,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 37,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 38,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 42,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 44.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 46.5,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 49,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 50,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 53,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 54,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 57,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 58,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 61,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 62,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 65,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 66,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 73,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 74,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 78,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 81,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 82,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 89,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 90,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 93.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 96,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 98,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 102.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 103,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 105,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 105.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 106,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 106,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 109.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 112,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 114,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 118.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 119,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 121,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 121.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 122,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 122,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 125.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 130,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 133,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 134,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 138,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 140.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 142.5,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 145,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 146,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 149,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 150,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 153,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 154,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 157,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 158,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 161,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 162,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 169,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 170,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 174,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 177,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 178,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 185,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 186,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 189.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 192,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 194,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 198.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 199,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 201,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 201.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 202,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 202,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 205.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 208,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 210,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 214.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 215,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 217,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 217.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 218,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 218,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 221.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 226,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 234,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 242,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 269,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 270,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 271,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 286,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 287,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 293.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 294,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 298.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 299,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 301,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 301.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 302,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 302,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 305.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 308,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 310,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 314.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 315,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 317,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 317.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 318,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 318,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 321.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 324,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 332,
    "m": 52,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1519
 },
 "stairway-hard": {
  "moves": [
   {
    "b": 2,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 4,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 18.5,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 20.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 33,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 38.5,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 39.5,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 41.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 50,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 51,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 51.5,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 53,
    "m": 59,
    "from": "R",
    "to": "L"
   },
   {
    "b": 55,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 55.5,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 56,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 58,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 60,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 67.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 69.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 70,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 71.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 72,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 73,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 73.5,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 75.5,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 76,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 77.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 78.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 84,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 86,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 86.5,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 88,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 88.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 89.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 90.5,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 92.5,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 93,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 94.5,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 95,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 100.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 101,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 101.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 105,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 106.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 107,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 108,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 108.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 109,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 111,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 117.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 119.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 120,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 121.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 122,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 123.5,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 125.5,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 126,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 127,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 128,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 134,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 136,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 136.5,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 138,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 138.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 139.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 140,
    "m": 54,
    "from": "R",
    "to": "L"
   },
   {
    "b": 142,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 142.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 144.5,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 145,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 149.5,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 153.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 170,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 171.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 187,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 188,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 199.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 202.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 203,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 204.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 205,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 206,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 206.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 207.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 208.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 210.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 216,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 217,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 219,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 219.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 221,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 221.5,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 222.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 223,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 224,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 225.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 226.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 227,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 241,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 242,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 257.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 258.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 270,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 273,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 273.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 275,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 275.5,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 276.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 277,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 278,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 279.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 281.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 286.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 287.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 289.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 290,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 291.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 292,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 293.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 294,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 295,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 296,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 297,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 297.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 311.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 312.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 313.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 328,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 329,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 330,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 340.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 341,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 343.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 345,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 347.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 349.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 350,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 352,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 357.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 358,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 360.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 362,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 362.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 364,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 366,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 366.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 368.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 382,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 383,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 398.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 399.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 411,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 411.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 414.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 416,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 416.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 418,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 420,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 420.5,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 422.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 428.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 429,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 431,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 432.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 434.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 436.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 437,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 439,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 457,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 479,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 483.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 488,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 495.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 496,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 497.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 499.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 501,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 501.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 507.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 514,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 528.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 537.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 539.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 550.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 550.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 552,
    "m": 55,
    "from": "R",
    "to": "L"
   },
   {
    "b": 564.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 570,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 572,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 574,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 574.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 575.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 576.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 578.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 583,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 584,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 584.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 586.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 591.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 592,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 593,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 595,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 597,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 599.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 600.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 601,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 603.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 605.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 606.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 611.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 613.5,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 620,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 622,
    "m": 50,
    "from": "R",
    "to": "L"
   },
   {
    "b": 632,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 647,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 647.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 649,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 650,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 650.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 654,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 655,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 656,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 657.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 658,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 658.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 659.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 662.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 665.5,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 668.5,
    "m": 59,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 3301
 },
 "fur-elise-full": {
  "moves": [
   {
    "b": 8,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 20.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 33,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 45.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 77,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 89,
    "m": 56,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 207
 },
 "arabesque-1-easy": {
  "moves": [
   {
    "b": 374,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 376.25,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 381.75,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 386,
    "m": 66,
    "from": "R",
    "to": "L"
   },
   {
    "b": 387.75,
    "m": 63,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 735
 },
 "arabesque-1-hard": {
  "moves": [
   {
    "b": 19.75,
    "m": 69,
    "from": "L",
    "to": "R"
   },
   {
    "b": 99.75,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299.75,
    "m": 69,
    "from": "L",
    "to": "R"
   },
   {
    "b": 406.25,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 407.25,
    "m": 61,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 1444
 },
 "clair-de-lune": {
  "moves": [
   {
    "b": 36,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 60.25,
    "m": 61,
    "from": "L",
    "to": "R"
   },
   {
    "b": 63.25,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 136.75,
    "m": 58,
    "from": "L",
    "to": "R"
   },
   {
    "b": 141.25,
    "m": 58,
    "from": "L",
    "to": "R"
   },
   {
    "b": 154.75,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 159.25,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 174.75,
    "m": 73,
    "from": "R",
    "to": "L"
   },
   {
    "b": 180.75,
    "m": 73,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181,
    "m": 76,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181.25,
    "m": 78,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181.5,
    "m": 76,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181.75,
    "m": 73,
    "from": "L",
    "to": "R"
   },
   {
    "b": 182,
    "m": 69,
    "from": "L",
    "to": "R"
   },
   {
    "b": 199.75,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 204.25,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 225.5,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 225.75,
    "m": 84,
    "from": "L",
    "to": "R"
   },
   {
    "b": 230.25,
    "m": 81,
    "from": "L",
    "to": "R"
   },
   {
    "b": 234.75,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 239.25,
    "m": 78,
    "from": "L",
    "to": "R"
   },
   {
    "b": 248.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 248.5,
    "m": 70,
    "from": "L",
    "to": "R"
   },
   {
    "b": 257.25,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 261,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 289,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 292.75,
    "m": 53,
    "from": "L",
    "to": "R"
   },
   {
    "b": 295.75,
    "m": 53,
    "from": "L",
    "to": "R"
   },
   {
    "b": 298.75,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299.5,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 301.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 304.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 308,
    "m": 71,
    "from": "L",
    "to": "R"
   },
   {
    "b": 308.25,
    "m": 76,
    "from": "L",
    "to": "R"
   },
   {
    "b": 311,
    "m": 71,
    "from": "L",
    "to": "R"
   },
   {
    "b": 311.25,
    "m": 76,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 977
 },
 "clair-de-lune-easy": {
  "moves": [
   {
    "b": 174.75,
    "m": 73,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 490
 },
 "clair-de-lune-hard": {
  "moves": [
   {
    "b": 54,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 58.5,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 60.25,
    "m": 61,
    "from": "L",
    "to": "R"
   },
   {
    "b": 115,
    "m": 72,
    "from": "L",
    "to": "R"
   },
   {
    "b": 136.75,
    "m": 58,
    "from": "L",
    "to": "R"
   },
   {
    "b": 141.25,
    "m": 58,
    "from": "L",
    "to": "R"
   },
   {
    "b": 154.75,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 159.25,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 174.75,
    "m": 73,
    "from": "R",
    "to": "L"
   },
   {
    "b": 180.75,
    "m": 73,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181,
    "m": 76,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181.25,
    "m": 78,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181.5,
    "m": 76,
    "from": "L",
    "to": "R"
   },
   {
    "b": 181.75,
    "m": 73,
    "from": "L",
    "to": "R"
   },
   {
    "b": 182,
    "m": 69,
    "from": "L",
    "to": "R"
   },
   {
    "b": 199.75,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 204.25,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 225.5,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 225.75,
    "m": 84,
    "from": "L",
    "to": "R"
   },
   {
    "b": 230.25,
    "m": 81,
    "from": "L",
    "to": "R"
   },
   {
    "b": 234.75,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 239.25,
    "m": 78,
    "from": "L",
    "to": "R"
   },
   {
    "b": 248.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 248.5,
    "m": 70,
    "from": "L",
    "to": "R"
   },
   {
    "b": 257.25,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 259,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 274.5,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 286,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 289,
    "m": 80,
    "from": "L",
    "to": "R"
   },
   {
    "b": 292.75,
    "m": 53,
    "from": "L",
    "to": "R"
   },
   {
    "b": 295.75,
    "m": 53,
    "from": "L",
    "to": "R"
   },
   {
    "b": 298.75,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299.5,
    "m": 68,
    "from": "L",
    "to": "R"
   },
   {
    "b": 301.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 304.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 308,
    "m": 71,
    "from": "L",
    "to": "R"
   },
   {
    "b": 308.25,
    "m": 76,
    "from": "L",
    "to": "R"
   },
   {
    "b": 311,
    "m": 71,
    "from": "L",
    "to": "R"
   },
   {
    "b": 311.25,
    "m": 76,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 1468
 },
 "coffin-dance": {
  "moves": [
   {
    "b": 76.25,
    "m": 38,
    "from": "R",
    "to": "L"
   },
   {
    "b": 262.5,
    "m": 55,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 1539
 },
 "coffin-dance-easy": {
  "moves": [
   {
    "b": 152.75,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 153.25,
    "m": 67,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 872
 },
 "disney-star": {
  "moves": [
   {
    "b": 154.25,
    "m": 43,
    "from": "R",
    "to": "L"
   },
   {
    "b": 243,
    "m": 46,
    "from": "R",
    "to": "L"
   },
   {
    "b": 250.25,
    "m": 63,
    "from": "R",
    "to": "L"
   },
   {
    "b": 252,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 252,
    "m": 73,
    "from": "L",
    "to": "R"
   },
   {
    "b": 266.75,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 268,
    "m": 78,
    "from": "L",
    "to": "R"
   },
   {
    "b": 425.25,
    "m": 46,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 484
 },
 "fantaisie-impromptu-hard": {
  "moves": [
   {
    "b": 168.25,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 188.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 220.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 268.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 316.25,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 536.75,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 537.75,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 538.75,
    "m": 53,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 3013
 },
 "goldberg-aria-hard": {
  "moves": [
   {
    "b": 22,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 43,
    "m": 64,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 415
 },
 "gymnopedie-1": {
  "moves": [
   {
    "b": 55,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 58,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 61,
    "m": 53,
    "from": "L",
    "to": "R"
   },
   {
    "b": 64,
    "m": 57,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 156
 },
 "gymnopedie-1-hard": {
  "moves": [
   {
    "b": 58,
    "m": 67,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 282
 },
 "imperial-march": {
  "moves": [
   {
    "b": 177.75,
    "m": 61,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 750
 },
 "jaws": {
  "moves": [
   {
    "b": 60.75,
    "m": 38,
    "from": "L",
    "to": "R"
   },
   {
    "b": 122.25,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 122.5,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 122.75,
    "m": 61,
    "from": "L",
    "to": "R"
   },
   {
    "b": 123.25,
    "m": 84,
    "from": "L",
    "to": "R"
   },
   {
    "b": 123.5,
    "m": 76,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 812
 },
 "jaws-easy": {
  "moves": [
   {
    "b": 100.75,
    "m": 51,
    "from": "R",
    "to": "L"
   },
   {
    "b": 154,
    "m": 62,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 338
 },
 "liebestraum-3-hard": {
  "moves": [
   {
    "b": 1,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 7,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 13,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 19,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 37,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 43,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 49,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 55,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 73,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 79,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 85,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 94,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 100,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 103,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 103,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 109,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 109,
    "m": 61,
    "from": "L",
    "to": "R"
   },
   {
    "b": 115,
    "m": 55,
    "from": "L",
    "to": "R"
   },
   {
    "b": 115,
    "m": 58,
    "from": "L",
    "to": "R"
   },
   {
    "b": 124,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 124,
    "m": 61,
    "from": "L",
    "to": "R"
   },
   {
    "b": 130,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 255.5,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 256,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 256.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 257,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 257.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 258.5,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 259,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 259.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 260,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 260.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 261.5,
    "m": 72,
    "from": "R",
    "to": "L"
   },
   {
    "b": 262.5,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 263,
    "m": 72,
    "from": "R",
    "to": "L"
   },
   {
    "b": 267.5,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 268,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 268.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 269,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 270.5,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 271,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 271.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 272,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 291.5,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 292,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 292.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 293,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 293.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 294.5,
    "m": 72,
    "from": "R",
    "to": "L"
   },
   {
    "b": 295.5,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 296,
    "m": 72,
    "from": "R",
    "to": "L"
   },
   {
    "b": 297.5,
    "m": 71,
    "from": "R",
    "to": "L"
   },
   {
    "b": 298,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 298.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 299,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 299.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 301.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 303.5,
    "m": 72,
    "from": "R",
    "to": "L"
   },
   {
    "b": 304,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 304.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 305,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 305.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 306.5,
    "m": 73,
    "from": "R",
    "to": "L"
   },
   {
    "b": 307,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 307.5,
    "m": 68,
    "from": "R",
    "to": "L"
   },
   {
    "b": 308,
    "m": 61,
    "from": "L",
    "to": "R"
   },
   {
    "b": 308.5,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 414,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 420,
    "m": 72,
    "from": "R",
    "to": "L"
   },
   {
    "b": 429,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 435,
    "m": 58,
    "from": "L",
    "to": "R"
   },
   {
    "b": 453,
    "m": 52,
    "from": "L",
    "to": "R"
   },
   {
    "b": 465,
    "m": 50,
    "from": "L",
    "to": "R"
   },
   {
    "b": 512.75,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 519,
    "m": 56,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 1884
 },
 "mozart-pc21-2-hard": {
  "moves": [
   {
    "b": 131,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 131.25,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 218,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 248,
    "m": 70,
    "from": "L",
    "to": "R"
   },
   {
    "b": 285.75,
    "m": 73,
    "from": "L",
    "to": "R"
   },
   {
    "b": 387,
    "m": 65,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 2474
 },
 "next-episode": {
  "moves": [
   {
    "b": 233.5,
    "m": 103,
    "from": "R",
    "to": "L"
   },
   {
    "b": 234.5,
    "m": 36,
    "from": "R",
    "to": "L"
   },
   {
    "b": 241,
    "m": 40,
    "from": "R",
    "to": "L"
   },
   {
    "b": 286.25,
    "m": 83,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 873
 },
 "overwatch": {
  "moves": [
   {
    "b": 91,
    "m": 94,
    "from": "R",
    "to": "L"
   },
   {
    "b": 125,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 194.75,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 272.5,
    "m": 35,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 515
 },
 "pain-easy": {
  "moves": [
   {
    "b": 146.25,
    "m": 77,
    "from": "R",
    "to": "L"
   },
   {
    "b": 196.75,
    "m": 61,
    "from": "R",
    "to": "L"
   },
   {
    "b": 317.5,
    "m": 73,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 601
 },
 "passacaglia-easy": {
  "moves": [
   {
    "b": 161.75,
    "m": 72,
    "from": "R",
    "to": "L"
   },
   {
    "b": 176.5,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 209.25,
    "m": 56,
    "from": "R",
    "to": "L"
   },
   {
    "b": 209.75,
    "m": 59,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 553
 },
 "prelude-e-minor": {
  "moves": [
   {
    "b": 70.75,
    "m": 69,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 257
 },
 "prelude-e-minor-hard": {
  "moves": [
   {
    "b": 70.75,
    "m": 69,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 600
 },
 "raindrop-prelude-hard": {
  "moves": [
   {
    "b": 8,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 11,
    "m": 61,
    "from": "R",
    "to": "L"
   },
   {
    "b": 12,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 15,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 24,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 27,
    "m": 61,
    "from": "R",
    "to": "L"
   },
   {
    "b": 28,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 35,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 84,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 87,
    "m": 61,
    "from": "R",
    "to": "L"
   },
   {
    "b": 88,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 89,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 91,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 100,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 135,
    "m": 52,
    "from": "L",
    "to": "R"
   },
   {
    "b": 199,
    "m": 52,
    "from": "L",
    "to": "R"
   },
   {
    "b": 308,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 311,
    "m": 61,
    "from": "R",
    "to": "L"
   },
   {
    "b": 312,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 315,
    "m": 60,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1516
 },
 "traumerei-hard": {
  "moves": [
   {
    "b": 2,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 2,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 18,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 29.5,
    "m": 67,
    "from": "L",
    "to": "R"
   },
   {
    "b": 34,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 34,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 50,
    "m": 58,
    "from": "R",
    "to": "L"
   },
   {
    "b": 50,
    "m": 62,
    "from": "L",
    "to": "R"
   },
   {
    "b": 66,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 66,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 82,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 82,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 86,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 94,
    "m": 55,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 339
 },
 "un-sospiro": {
  "moves": [
   {
    "b": 107.75,
    "m": 65,
    "from": "R",
    "to": "L"
   },
   {
    "b": 224.5,
    "m": 52,
    "from": "R",
    "to": "L"
   },
   {
    "b": 229.25,
    "m": 53,
    "from": "R",
    "to": "L"
   },
   {
    "b": 232.5,
    "m": 85,
    "from": "R",
    "to": "L"
   },
   {
    "b": 236,
    "m": 48,
    "from": "R",
    "to": "L"
   },
   {
    "b": 270.25,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 284.75,
    "m": 75,
    "from": "R",
    "to": "L"
   },
   {
    "b": 417.25,
    "m": 75,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 1214
 },
 "van-gogh": {
  "moves": [
   {
    "b": 231.5,
    "m": 62,
    "from": "R",
    "to": "L"
   },
   {
    "b": 232,
    "m": 77,
    "from": "L",
    "to": "R"
   },
   {
    "b": 232.75,
    "m": 48,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 336
 },
 "x-files": {
  "moves": [
   {
    "b": 19.25,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 33.5,
    "m": 60,
    "from": "L",
    "to": "R"
   },
   {
    "b": 165.25,
    "m": 45,
    "from": "R",
    "to": "L"
   },
   {
    "b": 165.5,
    "m": 33,
    "from": "R",
    "to": "L"
   },
   {
    "b": 167.5,
    "m": 33,
    "from": "R",
    "to": "L"
   },
   {
    "b": 172.75,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 174.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 175.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 176.5,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 188,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 189,
    "m": 57,
    "from": "L",
    "to": "R"
   },
   {
    "b": 190,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 190.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 191.75,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 196.5,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 205.75,
    "m": 76,
    "from": "L",
    "to": "R"
   },
   {
    "b": 206.25,
    "m": 59,
    "from": "L",
    "to": "R"
   },
   {
    "b": 210.25,
    "m": 56,
    "from": "L",
    "to": "R"
   },
   {
    "b": 212.5,
    "m": 63,
    "from": "L",
    "to": "R"
   },
   {
    "b": 213,
    "m": 67,
    "from": "L",
    "to": "R"
   },
   {
    "b": 272,
    "m": 79,
    "from": "L",
    "to": "R"
   },
   {
    "b": 278.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 323.5,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 327,
    "m": 66,
    "from": "L",
    "to": "R"
   },
   {
    "b": 398.5,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 401.5,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 403.25,
    "m": 65,
    "from": "L",
    "to": "R"
   },
   {
    "b": 419.5,
    "m": 64,
    "from": "L",
    "to": "R"
   }
  ],
  "notes": 968
 },
 "x-files-easy": {
  "moves": [
   {
    "b": 19.25,
    "m": 64,
    "from": "R",
    "to": "L"
   },
   {
    "b": 73.25,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 135,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 167.5,
    "m": 33,
    "from": "R",
    "to": "L"
   },
   {
    "b": 188,
    "m": 64,
    "from": "L",
    "to": "R"
   },
   {
    "b": 278.25,
    "m": 60,
    "from": "R",
    "to": "L"
   },
   {
    "b": 298.75,
    "m": 63,
    "from": "R",
    "to": "L"
   },
   {
    "b": 300,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 312.75,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 314.5,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 319.25,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 321.5,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 323.5,
    "m": 69,
    "from": "R",
    "to": "L"
   },
   {
    "b": 361.25,
    "m": 57,
    "from": "R",
    "to": "L"
   },
   {
    "b": 376.5,
    "m": 57,
    "from": "R",
    "to": "L"
   }
  ],
  "notes": 589
 }
};
