// Generated by tools/source-audit.mjs. Source onsets within 0.126 quarter beats; not editorial approval.
export const SOURCE_CHECKS = {
  "arabesque-1": {
    "songSignature": "1227:21290:55fdaccd",
    "sourceFile": "arabesque-1.mid",
    "sha256": "6732dc10799ec0af47d19d9095562d0671864a750129e0279901def169a34757",
    "notes": 1227,
    "sourceNotes": 1448,
    "matched": 1227,
    "missing": 221,
    "extra": 0,
    "durationMatches": 802,
    "handCompared": 1227,
    "handMatches": 1227,
    "maxOnsetError": 0.083333,
    "sourceBpm": 144,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "arabesque-1-easy": {
    "songSignature": "735:13227:ec5b6963",
    "sourceFile": "arabesque-1.mid",
    "sha256": "6732dc10799ec0af47d19d9095562d0671864a750129e0279901def169a34757",
    "notes": 735,
    "sourceNotes": 1448,
    "matched": 735,
    "missing": 713,
    "extra": 0,
    "durationMatches": 361,
    "handCompared": 735,
    "handMatches": 727,
    "maxOnsetError": 0.083333,
    "sourceBpm": 144,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "arabesque-1-hard": {
    "songSignature": "1444:25626:b7c8e004",
    "sourceFile": "arabesque-1.mid",
    "sha256": "6732dc10799ec0af47d19d9095562d0671864a750129e0279901def169a34757",
    "notes": 1444,
    "sourceNotes": 1448,
    "matched": 1444,
    "missing": 4,
    "extra": 0,
    "durationMatches": 826,
    "handCompared": 1444,
    "handMatches": 1410,
    "maxOnsetError": 0.083333,
    "sourceBpm": 144,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "bach-prelude-c-easy": {
    "songSignature": "448:8502:51eb6731",
    "sourceFile": "bach-prelude-c.mid",
    "sha256": "874e07d0479542971bfceaf420d6117da8d602d89d26eea4610e7dd1ef58bf26",
    "notes": 448,
    "sourceNotes": 549,
    "matched": 448,
    "missing": 101,
    "extra": 0,
    "durationMatches": 448,
    "handCompared": 448,
    "handMatches": 444,
    "maxOnsetError": 0,
    "sourceBpm": 60,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "bach-prelude-c-hard": {
    "songSignature": "549:10331:cc82dae4",
    "sourceFile": "bach-prelude-c.mid",
    "sha256": "874e07d0479542971bfceaf420d6117da8d602d89d26eea4610e7dd1ef58bf26",
    "notes": 549,
    "sourceNotes": 549,
    "matched": 549,
    "missing": 0,
    "extra": 0,
    "durationMatches": 549,
    "handCompared": 549,
    "handMatches": 545,
    "maxOnsetError": 0,
    "sourceBpm": 60,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "clair-de-lune": {
    "songSignature": "977:18332:ebae53a3",
    "sourceFile": "clair-de-lune.mid",
    "sha256": "4eee9a1546ffde1ff74cb9824ba0e57cbc821185a15185bfea9faed97820bf8c",
    "notes": 977,
    "sourceNotes": 1468,
    "matched": 66,
    "missing": 1402,
    "extra": 911,
    "durationMatches": 3,
    "handCompared": 66,
    "handMatches": 41,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      9,
      8
    ],
    "sourceKey": null
  },
  "clair-de-lune-easy": {
    "songSignature": "490:9008:48d7bbb0",
    "sourceFile": "clair-de-lune.mid",
    "sha256": "4eee9a1546ffde1ff74cb9824ba0e57cbc821185a15185bfea9faed97820bf8c",
    "notes": 490,
    "sourceNotes": 1468,
    "matched": 39,
    "missing": 1429,
    "extra": 451,
    "durationMatches": 2,
    "handCompared": 39,
    "handMatches": 18,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      9,
      8
    ],
    "sourceKey": null
  },
  "clair-de-lune-hard": {
    "songSignature": "1468:26863:67f90031",
    "sourceFile": "clair-de-lune.mid",
    "sha256": "4eee9a1546ffde1ff74cb9824ba0e57cbc821185a15185bfea9faed97820bf8c",
    "notes": 1468,
    "sourceNotes": 1468,
    "matched": 90,
    "missing": 1378,
    "extra": 1378,
    "durationMatches": 3,
    "handCompared": 90,
    "handMatches": 60,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      9,
      8
    ],
    "sourceKey": null
  },
  "consolation-3": {
    "songSignature": "874:16158:b2574f32",
    "sourceFile": "consolation-3.mid",
    "sha256": "0e5a927f5753e3e7edf7f271efeb0c802d7476bed69c696798a06c780c5a1bb7",
    "notes": 874,
    "sourceNotes": 1029,
    "matched": 874,
    "missing": 155,
    "extra": 0,
    "durationMatches": 361,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": "Db"
  },
  "consolation-3-easy": {
    "songSignature": "295:5141:28244f19",
    "sourceFile": "consolation-3.mid",
    "sha256": "0e5a927f5753e3e7edf7f271efeb0c802d7476bed69c696798a06c780c5a1bb7",
    "notes": 295,
    "sourceNotes": 1029,
    "matched": 295,
    "missing": 734,
    "extra": 0,
    "durationMatches": 259,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": "Db"
  },
  "consolation-3-hard": {
    "songSignature": "1029:19289:b49a1ba3",
    "sourceFile": "consolation-3.mid",
    "sha256": "0e5a927f5753e3e7edf7f271efeb0c802d7476bed69c696798a06c780c5a1bb7",
    "notes": 1029,
    "sourceNotes": 1029,
    "matched": 1029,
    "missing": 0,
    "extra": 0,
    "durationMatches": 397,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": "Db"
  },
  "fantaisie-impromptu": {
    "songSignature": "2276:43530:1b874b9c",
    "sourceFile": "fantaisie-impromptu.mid",
    "sha256": "b29f6add7473b6e931c2e66349e860bf0e884cf68e19e90420a4870aae689f96",
    "notes": 2276,
    "sourceNotes": 3014,
    "matched": 2276,
    "missing": 738,
    "extra": 0,
    "durationMatches": 1314,
    "handCompared": 2276,
    "handMatches": 2276,
    "maxOnsetError": 0.125,
    "sourceBpm": 131,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "fantaisie-impromptu-easy": {
    "songSignature": "1715:33205:a3393596",
    "sourceFile": "fantaisie-impromptu.mid",
    "sha256": "b29f6add7473b6e931c2e66349e860bf0e884cf68e19e90420a4870aae689f96",
    "notes": 1715,
    "sourceNotes": 3014,
    "matched": 1715,
    "missing": 1299,
    "extra": 0,
    "durationMatches": 1581,
    "handCompared": 1715,
    "handMatches": 1715,
    "maxOnsetError": 0.114583,
    "sourceBpm": 131,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "fantaisie-impromptu-hard": {
    "songSignature": "3013:58564:76088739",
    "sourceFile": "fantaisie-impromptu.mid",
    "sha256": "b29f6add7473b6e931c2e66349e860bf0e884cf68e19e90420a4870aae689f96",
    "notes": 3013,
    "sourceNotes": 3014,
    "matched": 3013,
    "missing": 1,
    "extra": 0,
    "durationMatches": 1733,
    "handCompared": 3013,
    "handMatches": 3013,
    "maxOnsetError": 0.125,
    "sourceBpm": 131,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "goldberg-aria": {
    "songSignature": "352:5965:e215931e",
    "sourceFile": "goldberg-aria.mid",
    "sha256": "05c6155d67e1ef5167eef113defabbc6c42a0fa0f74abe11c7d63258084d9a48",
    "notes": 352,
    "sourceNotes": 418,
    "matched": 352,
    "missing": 66,
    "extra": 0,
    "durationMatches": 289,
    "handCompared": 352,
    "handMatches": 352,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      3,
      4
    ],
    "sourceKey": "G"
  },
  "goldberg-aria-easy": {
    "songSignature": "236:4190:5b9a0530",
    "sourceFile": "goldberg-aria.mid",
    "sha256": "05c6155d67e1ef5167eef113defabbc6c42a0fa0f74abe11c7d63258084d9a48",
    "notes": 236,
    "sourceNotes": 418,
    "matched": 236,
    "missing": 182,
    "extra": 0,
    "durationMatches": 173,
    "handCompared": 236,
    "handMatches": 236,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      3,
      4
    ],
    "sourceKey": "G"
  },
  "goldberg-aria-hard": {
    "songSignature": "415:7177:6f324204",
    "sourceFile": "goldberg-aria.mid",
    "sha256": "05c6155d67e1ef5167eef113defabbc6c42a0fa0f74abe11c7d63258084d9a48",
    "notes": 415,
    "sourceNotes": 418,
    "matched": 415,
    "missing": 3,
    "extra": 0,
    "durationMatches": 325,
    "handCompared": 415,
    "handMatches": 411,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      3,
      4
    ],
    "sourceKey": "G"
  },
  "gymnopedie-1": {
    "songSignature": "156:2239:64fbb74e",
    "sourceFile": "gymnopedie-1.mid",
    "sha256": "09ce7337b4bf42ba12e1aa64b4c7dc7fcfa6455f1070cb12f8880a755df97384",
    "notes": 156,
    "sourceNotes": 282,
    "matched": 156,
    "missing": 126,
    "extra": 0,
    "durationMatches": 156,
    "handCompared": 156,
    "handMatches": 152,
    "maxOnsetError": 0,
    "sourceBpm": 60,
    "sourceMeter": [
      3,
      4
    ],
    "sourceKey": "Bm"
  },
  "gymnopedie-1-hard": {
    "songSignature": "282:4046:451bf8ee",
    "sourceFile": "gymnopedie-1.mid",
    "sha256": "09ce7337b4bf42ba12e1aa64b4c7dc7fcfa6455f1070cb12f8880a755df97384",
    "notes": 282,
    "sourceNotes": 282,
    "matched": 282,
    "missing": 0,
    "extra": 0,
    "durationMatches": 282,
    "handCompared": 282,
    "handMatches": 281,
    "maxOnsetError": 0,
    "sourceBpm": 60,
    "sourceMeter": [
      3,
      4
    ],
    "sourceKey": "Bm"
  },
  "nocturne-op9-2": {
    "songSignature": "783:14089:2890779",
    "sourceFile": "chopin-nocturne-op9-2.mid",
    "sha256": "e202d3941ce5f26397f57f59f0e2e4e3ad9e19061fa3c4dc596c5ee6a6a2548e",
    "notes": 783,
    "sourceNotes": 1242,
    "matched": 44,
    "missing": 1198,
    "extra": 739,
    "durationMatches": 0,
    "handCompared": 44,
    "handMatches": 43,
    "maxOnsetError": 0.125,
    "sourceBpm": 66,
    "sourceMeter": [
      12,
      8
    ],
    "sourceKey": "Eb"
  },
  "nocturne-op9-2-easy": {
    "songSignature": "419:7716:2dc4d62f",
    "sourceFile": "chopin-nocturne-op9-2.mid",
    "sha256": "e202d3941ce5f26397f57f59f0e2e4e3ad9e19061fa3c4dc596c5ee6a6a2548e",
    "notes": 419,
    "sourceNotes": 1242,
    "matched": 27,
    "missing": 1215,
    "extra": 392,
    "durationMatches": 0,
    "handCompared": 27,
    "handMatches": 26,
    "maxOnsetError": 0.125,
    "sourceBpm": 66,
    "sourceMeter": [
      12,
      8
    ],
    "sourceKey": "Eb"
  },
  "nocturne-op9-2-hard": {
    "songSignature": "1236:22039:ad0997c4",
    "sourceFile": "chopin-nocturne-op9-2.mid",
    "sha256": "e202d3941ce5f26397f57f59f0e2e4e3ad9e19061fa3c4dc596c5ee6a6a2548e",
    "notes": 1236,
    "sourceNotes": 1242,
    "matched": 75,
    "missing": 1167,
    "extra": 1161,
    "durationMatches": 0,
    "handCompared": 75,
    "handMatches": 74,
    "maxOnsetError": 0.125,
    "sourceBpm": 66,
    "sourceMeter": [
      12,
      8
    ],
    "sourceKey": "Eb"
  },
  "pathetique-2": {
    "songSignature": "819:15185:63a41e80",
    "sourceFile": "pathetique-2.mid",
    "sha256": "92c685ca98001473bcc21fa98110cc125ab489c1bf49be185e062d204a268492",
    "notes": 819,
    "sourceNotes": 1629,
    "matched": 819,
    "missing": 810,
    "extra": 0,
    "durationMatches": 509,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 36,
    "sourceMeter": [
      2,
      4
    ],
    "sourceKey": "Ab"
  },
  "pathetique-2-easy": {
    "songSignature": "578:10668:f0304833",
    "sourceFile": "pathetique-2.mid",
    "sha256": "92c685ca98001473bcc21fa98110cc125ab489c1bf49be185e062d204a268492",
    "notes": 578,
    "sourceNotes": 1629,
    "matched": 578,
    "missing": 1051,
    "extra": 0,
    "durationMatches": 357,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 36,
    "sourceMeter": [
      2,
      4
    ],
    "sourceKey": "Ab"
  },
  "pathetique-2-hard": {
    "songSignature": "1380:25620:13bb1bb8",
    "sourceFile": "pathetique-2.mid",
    "sha256": "92c685ca98001473bcc21fa98110cc125ab489c1bf49be185e062d204a268492",
    "notes": 1380,
    "sourceNotes": 1629,
    "matched": 1380,
    "missing": 249,
    "extra": 0,
    "durationMatches": 711,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 36,
    "sourceMeter": [
      2,
      4
    ],
    "sourceKey": "Ab"
  },
  "prelude-e-minor": {
    "songSignature": "257:4263:c7c1e276",
    "sourceFile": "prelude-e-minor.mid",
    "sha256": "c1d7e05aa4e6e2baeec2e9108402a969c16d5df302b82fd66d110634697f2e3b",
    "notes": 257,
    "sourceNotes": 600,
    "matched": 22,
    "missing": 578,
    "extra": 235,
    "durationMatches": 0,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0,
    "sourceBpm": 56,
    "sourceMeter": [
      2,
      2
    ],
    "sourceKey": "Em"
  },
  "prelude-e-minor-easy": {
    "songSignature": "105:1687:b1001c4c",
    "sourceFile": "prelude-e-minor.mid",
    "sha256": "c1d7e05aa4e6e2baeec2e9108402a969c16d5df302b82fd66d110634697f2e3b",
    "notes": 105,
    "sourceNotes": 600,
    "matched": 6,
    "missing": 594,
    "extra": 99,
    "durationMatches": 0,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0,
    "sourceBpm": 56,
    "sourceMeter": [
      2,
      2
    ],
    "sourceKey": "Em"
  },
  "prelude-e-minor-hard": {
    "songSignature": "600:10006:249ba4c9",
    "sourceFile": "prelude-e-minor.mid",
    "sha256": "c1d7e05aa4e6e2baeec2e9108402a969c16d5df302b82fd66d110634697f2e3b",
    "notes": 600,
    "sourceNotes": 600,
    "matched": 53,
    "missing": 547,
    "extra": 547,
    "durationMatches": 0,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0,
    "sourceBpm": 56,
    "sourceMeter": [
      2,
      2
    ],
    "sourceKey": "Em"
  },
  "raindrop-prelude": {
    "songSignature": "950:16175:69989563",
    "sourceFile": "raindrop-prelude.mid",
    "sha256": "bb9532e59bee378a42f0c53b64bf223ba4d6e261e00c1e2efb3ed8e023833bd9",
    "notes": 950,
    "sourceNotes": 1518,
    "matched": 950,
    "missing": 568,
    "extra": 0,
    "durationMatches": 926,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.114583,
    "sourceBpm": 80,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "raindrop-prelude-easy": {
    "songSignature": "626:10729:6107dec3",
    "sourceFile": "raindrop-prelude.mid",
    "sha256": "bb9532e59bee378a42f0c53b64bf223ba4d6e261e00c1e2efb3ed8e023833bd9",
    "notes": 626,
    "sourceNotes": 1518,
    "matched": 626,
    "missing": 892,
    "extra": 0,
    "durationMatches": 604,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.114583,
    "sourceBpm": 80,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "raindrop-prelude-hard": {
    "songSignature": "1516:25323:4fcd53e6",
    "sourceFile": "raindrop-prelude.mid",
    "sha256": "bb9532e59bee378a42f0c53b64bf223ba4d6e261e00c1e2efb3ed8e023833bd9",
    "notes": 1516,
    "sourceNotes": 1518,
    "matched": 1516,
    "missing": 2,
    "extra": 0,
    "durationMatches": 1473,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.114583,
    "sourceBpm": 80,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": null
  },
  "rondo-alla-turca": {
    "songSignature": "1089:19873:2f20917d",
    "sourceFile": "rondo-alla-turca.mid",
    "sha256": "c14299cbdd34c8b2081da84dc06519ef8a52a0d589ee53c758d28b8e3d727d1c",
    "notes": 1089,
    "sourceNotes": 1614,
    "matched": 1089,
    "missing": 525,
    "extra": 0,
    "durationMatches": 951,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      2,
      4
    ],
    "sourceKey": null
  },
  "rondo-alla-turca-easy": {
    "songSignature": "717:13142:83518bcc",
    "sourceFile": "rondo-alla-turca.mid",
    "sha256": "c14299cbdd34c8b2081da84dc06519ef8a52a0d589ee53c758d28b8e3d727d1c",
    "notes": 717,
    "sourceNotes": 1614,
    "matched": 717,
    "missing": 897,
    "extra": 0,
    "durationMatches": 652,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      2,
      4
    ],
    "sourceKey": null
  },
  "rondo-alla-turca-hard": {
    "songSignature": "1613:28935:9ec7f482",
    "sourceFile": "rondo-alla-turca.mid",
    "sha256": "c14299cbdd34c8b2081da84dc06519ef8a52a0d589ee53c758d28b8e3d727d1c",
    "notes": 1613,
    "sourceNotes": 1614,
    "matched": 1613,
    "missing": 1,
    "extra": 0,
    "durationMatches": 1304,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.125,
    "sourceBpm": 60,
    "sourceMeter": [
      2,
      4
    ],
    "sourceKey": null
  },
  "traumerei": {
    "songSignature": "241:3957:d3c7773d",
    "sourceFile": "traumerei.mid",
    "sha256": "6e0045d5783ff28dedcf05813074fe407ca3846e5e2a7246f2793ac5614e4851",
    "notes": 241,
    "sourceNotes": 339,
    "matched": 241,
    "missing": 98,
    "extra": 0,
    "durationMatches": 240,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.119792,
    "sourceBpm": 53,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": "F"
  },
  "traumerei-easy": {
    "songSignature": "148:2449:fa00c279",
    "sourceFile": "traumerei.mid",
    "sha256": "6e0045d5783ff28dedcf05813074fe407ca3846e5e2a7246f2793ac5614e4851",
    "notes": 148,
    "sourceNotes": 339,
    "matched": 148,
    "missing": 191,
    "extra": 0,
    "durationMatches": 147,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.119792,
    "sourceBpm": 53,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": "F"
  },
  "traumerei-hard": {
    "songSignature": "339:5467:2d599e24",
    "sourceFile": "traumerei.mid",
    "sha256": "6e0045d5783ff28dedcf05813074fe407ca3846e5e2a7246f2793ac5614e4851",
    "notes": 339,
    "sourceNotes": 339,
    "matched": 339,
    "missing": 0,
    "extra": 0,
    "durationMatches": 337,
    "handCompared": 0,
    "handMatches": 0,
    "maxOnsetError": 0.119792,
    "sourceBpm": 53,
    "sourceMeter": [
      4,
      4
    ],
    "sourceKey": "F"
  }
};
