// GENERATED by tools/record-tier-reasons.mjs. Do not hand-edit.
//
// Why a piece ships with fewer than three tiers. A machine transcription of a
// concert performance is not a piano arrangement: it holds notes no two hands
// can reach, and the playability audit refuses a tier rather than teach one.
// Recorded so a missing tier can be told apart from a tier nobody attempted.
export const TIERS_REFUSED = {
 "afterglow": {
  "tiers": 1,
  "notes": 1893,
  "why": "a fuller arrangement of this recording asks for 103 chords wider than 14 semitones, 27 moments with the hands crossed, 72 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "bach-prelude-c": {
  "tiers": 2,
  "notes": 549,
  "why": "engraved score, hands from the staves; Medium missing because no note count between 448 (Easy) and 549 (Hard) is a step down from both, or every cut that reaches it either fails the playability audit as the staves label the hands or does not sit between its neighbours on the library's difficulty scale"
 },
 "beanie": {
  "tiers": 2,
  "notes": 912,
  "why": "a fuller arrangement of this recording asks for 81 chords wider than 14 semitones, 13 moments with the hands crossed, 3 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "coffin-dance": {
  "tiers": 2,
  "notes": 2697,
  "why": "a fuller arrangement of this recording asks for 83 chords wider than 14 semitones, 24 moments with the hands crossed, 46 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "gray-day": {
  "tiers": 2,
  "notes": 488,
  "why": "a fuller arrangement of this recording asks for 26 chords wider than 14 semitones, 16 moments with the hands crossed, 3 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "gymnopedie-1": {
  "tiers": 2,
  "notes": 282,
  "why": "engraved score, hands from the staves; Easy missing because no cut reaches under 132 notes (a step down from Medium's 156) without dropping a beat's melody or bass"
 },
 "icarus": {
  "tiers": 1,
  "notes": 1967,
  "why": "a fuller arrangement of this recording asks for 225 chords wider than 14 semitones, 37 moments with the hands crossed, 81 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "idea-12": {
  "tiers": 2,
  "notes": 1145,
  "why": "a fuller arrangement of this recording asks for 131 chords wider than 14 semitones, 8 moments with the hands crossed, 16 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "imperial-march": {
  "tiers": 2,
  "notes": 3146,
  "why": "a fuller arrangement of this recording asks for 116 chords wider than 14 semitones, 35 moments with the hands crossed, 44 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "jaws": {
  "tiers": 2,
  "notes": 1373,
  "why": "a fuller arrangement of this recording asks for 86 chords wider than 14 semitones, 24 moments with the hands crossed, 31 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "last-waltz": {
  "tiers": 2,
  "notes": 1149,
  "why": "a fuller arrangement of this recording asks for 43 chords wider than 14 semitones, 11 moments with the hands crossed, 9 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "liebestraum-3": {
  "tiers": 2,
  "notes": 1851,
  "why": "a fuller arrangement of this recording asks for 19 chords wider than 14 semitones, 5 moments with the hands crossed, 16 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "little-things": {
  "tiers": 2,
  "notes": 964,
  "why": "a fuller arrangement of this recording asks for 52 chords wider than 14 semitones, 5 moments with the hands crossed, 1 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "mariage-d-amour": {
  "tiers": 2,
  "notes": 1739,
  "why": "a fuller arrangement of this recording asks for 58 chords wider than 14 semitones, 19 moments with the hands crossed, 9 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "moonlight-sonata": {
  "tiers": 2,
  "notes": 1142,
  "why": "engraved score, hands from the staves; Medium missing because no note count between 770 (Easy) and 1142 (Hard) is a step down from both, or every cut that reaches it either fails the playability audit as the staves label the hands or does not sit between its neighbours on the library's difficulty scale"
 },
 "never-gonna-2": {
  "tiers": 2,
  "notes": 272,
  "why": "a fuller arrangement of this recording asks for 2 chords wider than 14 semitones, 1 moments with the hands crossed, so the audit refused it rather than ship an unplayable tier"
 },
 "next-episode": {
  "tiers": 2,
  "notes": 2423,
  "why": "a fuller arrangement of this recording asks for 135 chords wider than 14 semitones, 38 moments with the hands crossed, 71 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "overwatch": {
  "tiers": 2,
  "notes": 3882,
  "why": "a fuller arrangement of this recording asks for 503 chords wider than 14 semitones, 94 moments with the hands crossed, 66 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "passacaglia": {
  "tiers": 2,
  "notes": 1178,
  "why": "a fuller arrangement of this recording asks for 106 chords wider than 14 semitones, 30 moments with the hands crossed, 12 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "say-yes-to-heaven": {
  "tiers": 2,
  "notes": 1887,
  "why": "a fuller arrangement of this recording asks for 188 chords wider than 14 semitones, 37 moments with the hands crossed, 21 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "un-sospiro": {
  "tiers": 2,
  "notes": 3091,
  "why": "a fuller arrangement of this recording asks for 313 chords wider than 14 semitones, 72 moments with the hands crossed, 46 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "valzer-d-inverno": {
  "tiers": 2,
  "notes": 1386,
  "why": "a fuller arrangement of this recording asks for 147 chords wider than 14 semitones, 25 moments with the hands crossed, 36 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "van-gogh": {
  "tiers": 2,
  "notes": 855,
  "why": "a fuller arrangement of this recording asks for 22 chords wider than 14 semitones, 13 moments with the hands crossed, 1 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "x-files": {
  "tiers": 2,
  "notes": 1174,
  "why": "a fuller arrangement of this recording asks for 127 chords wider than 14 semitones, 28 moments with the hands crossed, 8 jumps faster than 120 semitones a second, so the audit refused it rather than ship an unplayable tier"
 },
 "zeldas-lullaby": {
  "tiers": 2,
  "notes": 698,
  "why": "video-authored hands from the arranger's own render; Medium missing because thin('medium') keeps 656+ of Hard's 698 notes (not a step down) and no density cut between 317 and 593 notes exists without dropping a beat's melody or bass (every left-hand note is an outer voice of its beat)"
 }
};
