// QUARANTINE THE UNPLAYABLE TIERS. Mark, 2026-09-01: "quarantine the
// unplayable tiers" - his word, executing the 08-31 council's recommendation
// ("Quarantine, do not delete. Every clean tier and song stays immediately
// playable. The gate then genuinely fails on any NEW unambiguous defect,
// which is the only way it stays honest.")
//
// This reads the hand audit's findings and writes js/songs-quarantine.mjs:
// one entry per condemned tier, each carrying the audit's own measured words
// for WHY. songs.mjs stamps `quarantined` from that file and exports SHELF
// (the playable library) alongside SONGS (everything). The app shelves them;
// the data is untouched and fully recoverable - delete the entry and re-run
// this tool to bring a tier back after rework.
//
// ☠️ THE AUDIT MUST RUN UNQUARANTINED HERE. hand-audit.mjs skips quarantined
// songs (they are known, recorded decisions, not news), so regenerating this
// file from a quarantine-aware audit would see zero findings and write an
// empty quarantine, releasing all 77 tiers in one silent step. KEYS_RAW_QUARANTINE
// makes songs.mjs skip the stamping, so the audit judges the raw library.
//
//   node tools/quarantine.mjs [--dry]
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const dry = process.argv.includes('--dry');

process.env.KEYS_RAW_QUARANTINE = '1';
const { SONGS } = await import('file:///' + join(ROOT, 'js', 'songs.mjs').replace(/\\/g, '/'));
const byId = new Map(SONGS.map((s) => [s.id, s]));

let out = '';
try {
  out = execFileSync(process.execPath, [join(ROOT, 'tools', 'hand-audit.mjs'), '--all'], {
    encoding: 'utf8', env: { ...process.env, KEYS_RAW_QUARANTINE: '1' }, maxBuffer: 64 * 1024 * 1024,
  });
} catch (e) {
  // the audit exits 1 when it finds anything, which is exactly the case we want
  if (!e.stdout) throw e;
  out = e.stdout;
}

// section header -> kind slug, findings parsed off the audit's own lines so a
// reason here is always a measurement, never a judgement typed by hand
const KIND = {
  'CHORD NO HAND CAN HOLD': 'chord no hand can hold',
  'HAND CANNOT TRAVEL THAT FAST': 'hand cannot travel that fast',
  'THRESHOLD SPLIT': 'split by a pitch threshold',
  'CROSSED HANDS': 'crossed hands',
  'MORE THAN FIVE KEYS IN ONE HAND': 'more than five keys in one hand',
  'HAND ROAMS TOO FAR IN ONE BEAT': 'hand roams too far in one beat',
};
const bySong = new Map();
let kind = null;
for (const line of out.split('\n')) {
  const h = line.match(/^### (.+?) {2}\(/);
  if (h) { kind = KIND[h[1]] ?? null; continue; }
  if (/^guard$|^fixture:/.test(line.trim())) { kind = null; continue; }
  const m = line.match(/^ {2}([a-z0-9-]+) {2,}(.+)$/);
  if (m && kind && byId.has(m[1])) {
    if (!bySong.has(m[1])) bySong.set(m[1], []);
    bySong.get(m[1]).push(`${kind}: ${m[2].trim()}`);
  }
}

// structural validation, not length: an empty or misparsed audit must never
// silently write an empty quarantine over a full one
if (!bySong.size) {
  console.log('the audit reported no findings, so there is nothing to quarantine.');
  console.log('If tiers were quarantined before, they stay quarantined: refusing to overwrite.');
  process.exit(2);
}
for (const id of bySong.keys()) {
  if (!byId.has(id)) { console.log(`ABORT: audit names ${id}, which is not in SONGS`); process.exit(2); }
}

const entries = [...bySong.entries()].sort((a, b) => a[0].localeCompare(b[0]))
  .map(([id, whys]) => ` ${JSON.stringify(id)}: {\n  why: ${JSON.stringify(whys.join('; '))},\n },`);

const file = `// GENERATED by tools/quarantine.mjs. Do not hand-edit; re-run the tool.
//
// Tiers the hand audit condemns as unplayable, shelved on Mark's word
// (2026-09-01: "quarantine the unplayable tiers") per the 08-31 council.
// The note data still ships in the library files and every entry is
// recoverable: rework the arrangement, delete the entry, re-run the tool,
// and the tier returns to the shelf the moment the audit passes it.
export const QUARANTINE = {
${entries.join('\n')}
};
`;

// which pieces lose their whole shelf presence? say so every run, loudly
const groups = new Map();
for (const s of SONGS) { const g = s.group ?? s.id; if (!groups.has(g)) groups.set(g, []); groups.get(g).push(s.id); }
const wiped = [...groups.entries()].filter(([, ids]) => ids.every((id) => bySong.has(id)));

console.log(`${bySong.size} tiers quarantined across ${new Set([...bySong.keys()].map((id) => byId.get(id).group ?? id)).size} pieces`);
console.log(`${wiped.length} pieces have NO playable tier left and leave the shelf entirely:`);
for (const [g] of wiped) console.log(`  ${g}`);
if (dry) { console.log('\n--dry: nothing written'); process.exit(0); }
writeFileSync(join(ROOT, 'js', 'songs-quarantine.mjs'), file);
console.log('\nwrote js/songs-quarantine.mjs');
