// REPAIR THE HANDS OF SONGS A SCRIPT CUT IN HALF, offline, into a committed
// artifact.
//
// Codex's ruling, 2026-08-30, and the reason this is a tool and not a runtime
// pass: "Run it offline to produce proposed corrected note arrays, commit those
// arrays or a deterministic generated artifact, and retain provenance. The
// exported data should be the actual data the learner receives. Load time
// should validate, not repair."
//
// It only touches a song with BOTH pieces of evidence against it: the hands
// separate almost perfectly at a fixed pitch (a script, not an arranger) AND
// the result is unplayable. A clean split on its own is not evidence, because
// most simple piano writing puts the hands in separate registers; that mistake
// accused 36 innocent songs, the Gymnopedie and the Op.9 nocturne among them.
//
// And it refuses to touch a song carrying FINGERING. A finger number is
// authored against a hand, so moving the note to the other hand turns the
// fingering into a lie, and a wrong finger number is worse than none.
//
//   node tools/rehand.mjs           write js/songs-hands.mjs
//   node tools/rehand.mjs --dry     say what it would do
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SONGS } from '../js/songs.mjs';
import { repairHands, handsAreSane } from '../js/hands.mjs';

const dry = process.argv.includes('--dry');

// ☠️ A VERIFIED PIN OUTRANKS THE AUDIT. test/check.mjs pins the opening figures
// of songs that were checked against real sources, and those pins encode
// musical truth this tool cannot see: reassigning Moonlight's hands moved the
// famous right-hand triplet into the left, and the pin caught it. Codex warned
// exactly this ("fails a crude playability audit" does not prove "safe for
// automatic reassignment") and it was right. A song is only repaired if every
// pin still passes afterwards; anything that breaks one is listed here with
// what it broke, and left alone.
const PINNED_AND_WRONG = {
  'moonlight-sonata': 'reassignment moved the opening right-hand triplet into the left hand',
  'in-the-end': 'reassignment broke the verified Hooktheory riff degrees 1-5-5-3-2-2 in Em',
};

const cleanSplit = (notes) => {
  const L = notes.filter((n) => n.h === 'L').map((n) => n.m);
  const R = notes.filter((n) => n.h === 'R').map((n) => n.m);
  if (L.length < 20 || R.length < 20) return 0;
  let best = 0;
  for (let cut = 24; cut <= 96; cut++) {
    const ok = L.filter((m) => m < cut).length + R.filter((m) => m >= cut).length;
    best = Math.max(best, ok / (L.length + R.length));
  }
  return best;
};

const fixes = {};
const skipped = [];
let considered = 0;

for (const song of SONGS) {
  const notes = song.notes || [];
  if (notes.length < 40) continue;
  const bpm = song.bpm || 100;
  const fromScore = song.handAssignment === 'generated';
  if (handsAreSane(notes, bpm, fromScore)) continue;          // playable: leave it alone
  if (cleanSplit(notes) <= 0.985) { skipped.push([song.id, 'unplayable, but not a threshold split: the arrangement is the problem, not the hands']); continue; }
  considered++;
  if (PINNED_AND_WRONG[song.id]) { skipped.push([song.id, 'a verified test pin says otherwise: ' + PINNED_AND_WRONG[song.id]]); continue; }
  if (notes.some((n) => n.f != null)) { skipped.push([song.id, 'carries fingering, which is authored against a hand: reassigning would make it false']); continue; }

  const copy = notes.map((n) => ({ ...n }));
  repairHands(copy, bpm);
  if (!handsAreSane(copy, bpm)) { skipped.push([song.id, 'still unplayable after reassignment: more material than two hands can take']); continue; }
  fixes[song.id] = { hands: copy.map((n) => n.h).join(''), notes: copy.length };
}

const ids = Object.keys(fixes);
console.log(`${considered} songs were script-split AND unplayable; ${ids.length} of them can be repaired by reassigning hands\n`);
for (const id of ids) console.log(`  REPAIR  ${id.padEnd(28)} ${fixes[id].notes} notes`);
console.log('');
for (const [id, why] of skipped) console.log(`  leave   ${id.padEnd(28)} ${why}`);

if (dry) { console.log('\n--dry: nothing written'); process.exit(0); }
if (!ids.length) { console.log('\nnothing to write'); process.exit(0); }

const body = `// GENERATED by tools/rehand.mjs. Do not hand-edit: re-run the tool.
//
// These songs had their hands cut by a PITCH THRESHOLD rather than arranged, and
// the result was physically unplayable: a right hand holding chords wider than a
// hand and travelling further than a hand moves. Each entry below is that song's
// hands re-derived by js/hands.mjs and then checked, note for note, in the order
// the song's own notes array is authored.
//
// This is committed data, not a repair that runs at load: what the learner
// receives is what is in the file. songs.mjs applies it and asserts the length
// matches, so a song edited without re-running this tool fails loudly instead of
// being silently mis-handed.
export const REHANDED = ${JSON.stringify(fixes, null, 1)};
`;
writeFileSync(join(import.meta.dirname, '..', 'js', 'songs-hands.mjs'), body);
console.log(`\nwrote js/songs-hands.mjs with ${ids.length} corrected songs`);
