// Run the meter model over every song that has a pulse sidecar, and write the
// confident answers into js/songs-meter.mjs for the app to use.
//
//   node write-meter.mjs [--dry]
//
// ☠️ THE THRESHOLD BELOW WAS FITTED, NOT PRE-COMMITTED, AND THAT IS A WEAKER
// CLAIM. Gate 0's beat thresholds were fixed before results (council rule) and
// held. This one was chosen after seeing nine songs, because the separation was
// too clean to ignore: every correct answer scored margin 0.344 to 4.238, and
// the single wrong one (Jaws, called 3/4 when it is 4/4) scored 0.064. So the
// bar is set where the evidence actually splits, and it is honest to say the
// number is calibrated rather than proven. It needs songs it has never seen to
// become a real threshold - each new import is one, and a wrong meter is
// visible to Mark instantly because he counts along.
//
// What is NOT claimed: downbeat TIMES. Gate 1's timing arm still fails (F1 0.19
// vs the pre-committed 0.60) because librosa's beat COUNT between bars is not
// constant - it inserts and drops beats - so counting modulo a bar length
// desynchronises over minutes. Meter is a single number per song and survives
// that; bar LINES do not. Songs get their time signature here, not bar lines.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { parseMidi, midiNotes } from 'file:///C:/Users/markh/keys-piano/tools/midi.mjs';
import { inferMeter } from './meter.mjs';

const W = 'C:/Users/markh/keys-piano-tools/workshop';
const OUT = 'C:/Users/markh/keys-piano/js/songs-meter.mjs';
const MARGIN_MIN = 0.30;      // see the note above: fitted, not pre-committed
const STRENGTH_MIN = 2.0;
const dry = process.argv.includes('--dry');

const { SONGS } = await import('file:///C:/Users/markh/keys-piano/js/songs.mjs');
// which workshop file did each song group come from? the source line records it
const groups = new Map();
for (const s of SONGS) {
  const g = s.group ?? s.id;
  if (!groups.has(g)) groups.set(g, s);
}

const out = {};
const rows = [];
for (const [g, song] of groups) {
  // a group's audio may be filed under the group slug or a named variant
  const stem = [g, `${g}-kyle`, `${g}-full`].find((x) => existsSync(`${W}/${x}.beats.json`) && existsSync(`${W}/${x}.mid`));
  if (!stem) continue;
  const sc = JSON.parse(readFileSync(`${W}/${stem}.beats.json`, 'utf8'));
  const notes = midiNotes(parseMidi(readFileSync(`${W}/${stem}.mid`))).map((x) => ({ t: x.b * 0.5, m: x.m, vel: x.vel }));
  const r = inferMeter(sc, notes);
  if (!r.ok) { rows.push([g, 'refused', r.why]); continue; }
  const confident = r.barMargin >= MARGIN_MIN && r.barStrength >= STRENGTH_MIN;
  rows.push([g, confident ? `${r.meter}/4` : `held (${r.meter}/4?)`,
    `margin ${r.barMargin} strength ${r.barStrength} beat ${r.beatBpm}bpm`]);
  if (confident) out[g] = { meter: r.meter, beatBpm: r.beatBpm, barSec: r.barSec, margin: r.barMargin, from: stem };
}

for (const [g, verdict, why] of rows.sort()) console.log(`${g.padEnd(22)} ${verdict.padEnd(14)} ${why}`);
console.log(`\n${Object.keys(out).length} confident of ${rows.length} measured`);

const body = `// GENERATED by keys-piano-tools/write-meter.mjs. Do not hand-edit.
//
// Time signatures HEARD from the source recordings, not assumed. The
// transcriber emits no meter at all, so without this every transcribed song
// wore a 120bpm 4/4 grid and Married Life - a waltz - counted in four until
// Mark heard it and said so.
//
// Only songs whose evidence separates clearly appear here; the rest stay
// "free time" and show no time signature, which is the honest state. Keyed by
// song GROUP, since tiers share one recording.
export const METER = ${JSON.stringify(out, null, 1)};
`;
if (dry) console.log('\n--dry: nothing written');
else { writeFileSync(OUT, body); console.log(`\nwrote ${OUT}`); }
